name: docker-symfony
services:
    nginx-8008: # Your Nginx service name
        image: kprimecity/docker-symfony-nginx:latest
        container_name: docker-symfony-nginx-8008 # Your Container name
        restart: unless-stopped
        environment:
            - PGID=1000
            - PUID=1000
            - PHP_SERVICE_NAME=php-8008 # This Value MUST be as the php service name bellow
        ports:
            - 8008:80 # You still need to use https://xx.xx.xx.xx:8008 even if you bind 80 port
            - 8043:443 # Optional
        volumes:
            - ./path/to/web/conf/8008:/etc/nginx/conf.d # Mount Nginx config
        depends_on:
            - php-8008 # Same as PHP_SERVICE_NAME environment
        networks:
            - docker-symfony-network

    php-8008: # PHP service name: Same as PHP_SERVICE_NAME environment ABOVE
        image: kprimecity/docker-symfony-php:latest
        container_name: docker-symfony-php-8008 # Your Container name
        restart: unless-stopped
        environment:
            - PGID=1000
            - PUID=1000
        volumes:
            - ./path/to/web/html:/var/www/html # Mount html content to manage your project locally
        networks:
            - docker-symfony-network
networks:
    docker-symfony-network:
        name: docker-symfony-network
        driver: bridge
    default:
        name: docker-symfony_default
