name: "docker-symfony"

services:
  docker-symfony-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: docker-symfony-nginx:latest
    container_name: docker-symfony-nginx
    environment:
      - PGID=1000
      - PUID=1000
      - PHP_SERVICE_NAME=docker-symfony-php
      - NGINX_SERVER_NAME=your-server-name
    ports:
      - "80:80"
      - "443:443" # Optional
    volumes:
      - /path/to/your/web/conf:/etc/nginx/conf.d # Mount Nginx config
    depends_on:
      - docker-symfony-php
    networks:
      - docker-symfony-network

  docker-symfony-php:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: docker-symfony-php:latest
    container_name: docker-symfony-php
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - "9000:9000" # Optional
    volumes:
      - /path/to/your/web/html:/var/www/html # Mount html content
    networks:
      - docker-symfony-network
networks:
  docker-symfony-network:
    driver: bridge
