name: docker-symfony
services:
    symfony-8008: # service name
        image: kprimecity/docker-symfony:latest
        container_name: symfony-8008 # Your Container name
        restart: always
        ports:
            - 8008:80 # http://xx.xx.xx.xx:8008
            - 8043:443 # Optional: https://xx.xx.xx.xx:8043
        volumes:
            - /path/to/html/nginx/8008:/etc/nginx/http.d # Mount Nginx config.
            - /path/to/html/web:/var/www/html/web # Mount the Symfony html content
        networks:
            - docker-symfony-network

networks:
    docker-symfony-network:
        name: docker-symfony-network
        driver: bridge
    default:
        name: docker-symfony_default
